class Roles:
    EMPLOYEE = "EMPLOYEE"
    TEAM_LEAD = "TEAM_LEAD"
    ADMIN = "ADMIN"
    LOGISTICS = "LOGISTICS"


class MealTypes:
    LUNCH = "LUNCH"
    SNACKS = "SNACKS"
    IFTAR = "IFTAR"
    EVENT_DINNER = "EVENT_DINNER"
    OPTIONAL_DINNER = "OPTIONAL_DINNER"

    ALL = [LUNCH, SNACKS, IFTAR, EVENT_DINNER, OPTIONAL_DINNER]


class Locations:
    OFFICE = "OFFICE"
    WFH = "WFH"


class SpecialDayTypes:
    OFFICE_CLOSED = "OFFICE_CLOSED"
    GOVT_HOLIDAY = "GOVT_HOLIDAY"
    CELEBRATION = "CELEBRATION"
